Allow the user to delete his own account.
guiUrbanas03/fk-royale-backend pull request #5
Opened 2023-08-24 15:30 UTC by Leo-MouraF

Hey boss! The taks is done. I think have some issues to solve, but we can talk later. xoxo.

2023-08-24 21:18 UTC, guiUrbanas03 commented
@Leo-MouraF Congratulations for concluding the task, the account deletion is working as expected! There are just some details that I noticed that we could make it better. Please, check the comments that I left in the code on the "Files changed" section.

2023-08-24 21:19 UTC, guiUrbanas03 commented on source/blueprints/user/services.py
> +    if answer == "yes":
The logic of receiving a "confirm_deletion" flag is correct, but we don't need to have it in the backend, in this context this is a concern of the frontend, so we can securely remove it here.

2023-08-24 21:31 UTC, guiUrbanas03 requested changes

2023-08-24 21:31 UTC, guiUrbanas03 commented on source/blueprints/user/routes.py
> +        {
Just for a matter of keeping the patterns, in the data response dict replace the keys "User", "Profile", "Game Stats" with "user", "profile" and "game_stats", respectively.

2023-08-25 16:45 UTC, Leo-MouraF commented
Hey boss. I've already done the changes that you asked me. I think you'll find a problem. I'm pasting the code here, so this ways you can see exactly what i mean.
def user_del():
    """Allow the user to delete his own account"""

    try:
        if not current_user.deleted_at:
            delete_user()
            db.session.commit()
            
        else:   
            return 'User already deleted.'

So, here I imagine that we don't need the "else", but when i tried to make run without this else, didn't run correctly.

2023-08-26 08:33 UTC, guiUrbanas03 requested changes

2023-08-26 08:33 UTC, guiUrbanas03 commented on source/blueprints/user/routes.py
> +            return 'User already deleted.'
Just a small tweak here,  replace `return 'User already deleted.'` with the following code:

```
abort(409, {"type": CauseTypeError.DATA_VIOLATION_ERROR.value, "data": "User already deleted."})
```

Note that I choose the **409 status code**  - which stands for **CONFLICT**.

In this app, usually when we are sending a **successful response** we are going to use the `DataResponse` class, and when we are sending a **error response** we are going to use the `abort()` function.

Let me know if you have any questions about it.

2023-08-26 08:44 UTC, guiUrbanas03 commented
> Hey boss. I've already done the changes that you asked me. I think you'll find a problem. I'm pasting the code here, so this ways you can see exactly what i mean. def user_del(): """Allow the user to delete his own account"""
> 
> ```
> try:
>     if not current_user.deleted_at:
>         delete_user()
>         db.session.commit()
>         
>     else:   
>         return 'User already deleted.'
> ```
> 
> So, here I imagine that we don't need the "else", but when i tried to make run without this else, didn't run correctly.

In this situation we really need to have the else statement because the code inside the if block doesn't return, raise or break the flow when a user that is already deleted tries to delete himself again.

But there's something that we could do better in regards the "User already deleted" message, please refer to this comment to see the details:
https://github.com/guiUrbanas03/fk-royale-backend/pull/5#discussion_r1306378261

2023-08-26 08:58 UTC, guiUrbanas03 requested changes

2023-08-26 08:58 UTC, guiUrbanas03 commented on source/blueprints/user/routes.py
> +def user_del():
Juuust another really small tweak here too, prefer to use descriptive names for the functions:
`def delete_user()` it's likely cleaner and more readable than names such as `user_del` or `del_user`.

2023-08-30 13:30 UTC, merged